name: dynamic_persona_frontend
description: A production-grade Flutter web SPA for dynamic persona chat application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.0
  uuid: ^3.0.7
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Add assets here for the new Orizon UI
  assets:
    - assets/

  # Custom fonts for the Orizon design (commented out until font files are available)
  fonts:
    - family: NouvelR
      fonts:
        - asset: fonts/NouvelR-Regular.ttf
          weight: 400
        - asset: fonts/NouvelR-Light.ttf
          weight: 300
        - asset: fonts/NouvelR-Book.ttf
          weight: 500
        - asset: fonts/NouvelR-Bold.ttf
          weight: 700
